default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: 1234
  pool: 5

development:
  <<: *default
  database: mail_sending_service_development

test:
  <<: *default
  database: mail_sending_service_test

production:
  primary:
    <<: *default
    database: mail_sending_service_production
    username: postgres
    password: 1234

  cable:
    <<: *default
    database: mail_sending_service_production

  queue:
    <<: *default
    database: mail_sending_service_production

  cache:
    <<: *default
    database: mail_sending_service_production