default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: host.docker.internal
  port: 5432
  username: postgres
  password: 1234
  database: mail_sending_service_development

test:
  <<: *default
  host: host.docker.internal
  port: 5432
  username: postgres
  password: 1234
  database: mail_sending_service_test

production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>

  cable:
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    url: <%= ENV["DATABASE_URL"] %>