name: Auto Deploy Rails to EC2

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t yashwardhan24/mail_sending_service .

    - name: Push Docker Image
      run: docker push yashwardhan24/mail_sending_service

    - name: Deploy on EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3

      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |

          echo "Deploy started"

          docker stop mail_app || true
          docker rm mail_app || true

          docker pull yashwardhan24/mail_sending_service

          docker run -d \
            -p 80:8080 \
            --name mail_app \
            --restart always \
            yashwardhan24/mail_sending_service

          echo "Deploy finished"